/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.Asignatura.Asignatura;
import Datos.Aula.Aula;
import Datos.Horario.Dia;
import Datos.Horario.Horario;
import Negocio.ArchivoCls;
import Negocio.AulaCls;
import Negocio.CalendarioCls;
import Negocio.DepartamentoCls;
import Negocio.UsuarioCls;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultDesktopManager;
import javax.swing.DesktopManager;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author GeOrge
 */
public class frmCalendario extends javax.swing.JFrame {

    /**
     * Creates new form frmCalendario
     */
    public frmCalendario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        cmbSemestre = new javax.swing.JComboBox();
        pnlDesktop = new javax.swing.JDesktopPane();
        frmInterno = new javax.swing.JInternalFrame();
        lblCabeza1 = new javax.swing.JLabel();
        lblDato1 = new javax.swing.JLabel();
        lblDato2 = new javax.swing.JLabel();
        lblCabeza2 = new javax.swing.JLabel();
        lblDato3 = new javax.swing.JLabel();
        lblCabeza3 = new javax.swing.JLabel();
        lblDato4 = new javax.swing.JLabel();
        lblCabeza4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHorario = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmbSemestre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Primero", "Segundo" }));

        pnlDesktop.setPreferredSize(new java.awt.Dimension(490, 100));

        frmInterno.setClosable(true);
        frmInterno.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        frmInterno.setResizable(true);
        frmInterno.setVisible(true);

        lblCabeza1.setText("jLabel1");

        lblDato1.setText("jLabel2");

        lblDato2.setText("jLabel2");

        lblCabeza2.setText("jLabel1");

        lblDato3.setText("jLabel2");

        lblCabeza3.setText("jLabel1");

        lblDato4.setText("jLabel2");

        lblCabeza4.setText("jLabel1");

        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmInternoLayout = new javax.swing.GroupLayout(frmInterno.getContentPane());
        frmInterno.getContentPane().setLayout(frmInternoLayout);
        frmInternoLayout.setHorizontalGroup(
            frmInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmInternoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frmInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmInternoLayout.createSequentialGroup()
                        .addComponent(lblCabeza1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDato1))
                    .addGroup(frmInternoLayout.createSequentialGroup()
                        .addComponent(lblCabeza2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDato2))
                    .addGroup(frmInternoLayout.createSequentialGroup()
                        .addComponent(lblCabeza3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDato3))
                    .addGroup(frmInternoLayout.createSequentialGroup()
                        .addComponent(lblCabeza4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDato4)))
                .addContainerGap(240, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmInternoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2))
        );
        frmInternoLayout.setVerticalGroup(
            frmInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmInternoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frmInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCabeza1)
                    .addComponent(lblDato1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frmInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCabeza2)
                    .addComponent(lblDato2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frmInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCabeza3)
                    .addComponent(lblDato3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frmInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCabeza4)
                    .addComponent(lblDato4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jButton2))
        );

        frmInterno.setBounds(210, 90, 340, 150);
        pnlDesktop.add(frmInterno, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 20));

        tblHorario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Curso", "Horario", "Aula", "Profesor"
            }
        ));
        tblHorario.setPreferredSize(new java.awt.Dimension(500, 20));
        tblHorario.setShowHorizontalLines(false);
        tblHorario.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tblHorario);

        jScrollPane1.setBounds(0, 0, 630, 290);
        pnlDesktop.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cmbSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        frmInterno.setVisible(false);
        this.setTitle("Horario");
        lblCabeza1.setVisible(false);
        lblCabeza2.setVisible(false);
        lblCabeza3.setVisible(false);
        lblCabeza4.setVisible(false);
        lblDato1.setVisible(false);
        lblDato2.setVisible(false);
        lblDato3.setVisible(false);
        lblDato4.setVisible(false);
        
        ArchivoCls insArchivo = new ArchivoCls();
        insArchivo.cargar();
        CalendarioCls insCalendario = new CalendarioCls();            
        insCalendario.reset();
        ArrayList<Asignatura> calendario = insCalendario.crear(DepartamentoCls.getDepartamento(), UsuarioCls.getUsuario(), AulaCls.getAula(), V_Coordinador.jCombo_Semestre.getSelectedIndex());
        
        String horaInicial = "";
        String horaFinal = "";
        String dia = "";
        String[] columns = {"Curso","Aula","Horario","Profesor"};
        ArrayList<Vector> data = new ArrayList<>();
        
        tblHorario.setPreferredSize(new Dimension(500, 20));
        TableCellRenderer defaultRenderer = tblHorario.getDefaultRenderer(JButton.class);
        tblHorario.setDefaultRenderer(JButton.class, new TableButtonRenderer(defaultRenderer));
        tblHorario.addMouseListener(new TableButtonMouseListener(tblHorario));
        
        
        
        for(int i=0; i < calendario.size(); i++) {
            tblHorario.setPreferredSize(new Dimension(500, tblHorario.getPreferredSize().height+16));
            Vector vector = new Vector();
            
            JButton b1 = new JButton(calendario.get(i).getCodigo());
            b1.setBorderPainted(false);
            vector.add(b1);
            JButton b2 = new JButton(calendario.get(i).getAula().get(0).getNombre());
            b2.setBorderPainted(false);
            vector.add(b2);
            boolean bandera = false;
            for(int j=0; j < calendario.get(i).getHorario().size(); j++) {
                dia = calendario.get(i).getHorario().get(j).getDia();
                for(int k=0; k < calendario.get(i).getHorario().get(j).getHorario().size(); k++) {
                    if(!calendario.get(i).getHorario().get(j).getHorario().get(k).isEstado()) {
                        horaInicial = calendario.get(i).getHorario().get(j).getHorario().get(k).getHoraInicio();
                        horaFinal = calendario.get(i).getHorario().get(j).getHorario().get(k).getHoraFinal();
                        bandera = true;
                        break;
                    }
                }
                if(bandera)
                    break;
            }
            vector.add(new JButton("Schedule"));
            vector.add(UsuarioCls.getProfesorporAsignatura(calendario.get(i).getCodigo()).getNombre());
            data.add(vector);
        }
        tblHorario.setModel(new TableButtonModel(data,columns));
    }//GEN-LAST:event_formComponentShown

    private static void datos(String[] cabeza, String[] datos) {
        int tamano=0;
        for(int i=0; i < datos.length; i++) {
            if((cabeza[i]+datos[i]).length() > tamano)
                tamano = (cabeza[i]+datos[i]).length();
            switch (i) {
                case 0:
                    lblCabeza1.setText(cabeza[i]);
                    lblCabeza1.setVisible(true);
                    lblDato1.setText(datos[i]);
                    lblDato1.setVisible(true);
                    break;
                case 1:
                    lblCabeza2.setText(cabeza[i]);
                    lblCabeza2.setVisible(true);
                    lblDato2.setText(datos[i]);
                    lblDato2.setVisible(true);
                    break;
                case 2:
                    lblCabeza3.setText(cabeza[i]);
                    lblCabeza3.setVisible(true);
                    lblDato3.setText(datos[i]);
                    lblDato3.setVisible(true);
                    break;
                case 3:
                    lblCabeza4.setText(cabeza[i]);
                    lblCabeza4.setVisible(true);
                    lblDato4.setText(datos[i]);
                    lblDato4.setVisible(true);
                    break;
            }
        }
        
        frmInterno.setSize(new Dimension(tamano*9, frmInterno.getSize().height));
    }
    public static void frmInterna(String codigo, int columna) {
        DesktopManager manager = new DefaultDesktopManager() {
            @Override
            public void setBoundsForFrame(JComponent f, int newX, int newY, int newWidth, int newHeight) {
                boolean didResize = (f.getWidth() != newWidth || f.getHeight() != newHeight);
                if (!inBounds((JInternalFrame) f, newX, newY, newWidth, newHeight)) return;
                f.setBounds(newX, newY, newWidth, newHeight);
                if(didResize) {
                    f.validate();
                } 
            }

            protected boolean inBounds(JInternalFrame f, int newX, int newY, int newWidth, int newHeight) {
                if (newX < 0 || newY < 0) return false;
                if (newX + newWidth > f.getDesktopPane().getWidth()) return false;
                if (newY + newHeight > f.getDesktopPane().getHeight()) return false;
                return true;
            }
        };
        
        pnlDesktop.setDesktopManager(manager);
        frmInterno.setLocation(200, 100);
        frmInterno.setSize(new Dimension(200, 150));
        frmInterno.moveToFront();
        
        String[] datos;
        String[] cabeza;
        switch(columna) {
            case 0:
                Asignatura curso = DepartamentoCls.getAsig(codigo);
                cabeza = new String[] {"Id: ", "Name: ", "Group: ", "Credits: ", "Semester: "};
                datos = new String[] {codigo, 
                                      curso.getNombre(), 
                                      String.valueOf(curso.getGrupo()), 
                                      String.valueOf(curso.getCreditos()),
                                      String.valueOf(curso.getSemestre())};
                datos(cabeza, datos);
                break;
            case 1:
                ArrayList<Aula> aula = DepartamentoCls.getAula(codigo);
                cabeza = new String[] {"Name: ", "Number: ", "Location: ", "Capacity: "};
                String nombre="", numero="", ubicacion="", capacidad="";
                if(!aula.isEmpty()) {
                    for(int x=0; x < aula.size(); x++) {
                        nombre = aula.get(x).getNombre();
                        numero = String.valueOf(aula.get(x).getNumero());
                        ubicacion = aula.get(x).getUbicacion();
                        capacidad = String.valueOf(aula.get(x).getCapacidad());
                    }
                }
                datos = new String[] {nombre, numero, ubicacion, capacidad}; 
                datos(cabeza, datos);
                break;
            case 2:
                ArrayList<Dia> horario = DepartamentoCls.getHorario(codigo);
                cabeza = new String[] {"Day: ", "Time: "};
                String dia="", hora="";
                if(!horario.isEmpty()) {
                    for(int x=0; x < horario.size(); x++) {
                        dia = horario.get(x).getDia();
                        for(int y=0; y < horario.get(x).getHorario().size(); y++) {
                            if(!horario.get(x).getHorario().get(y).isEstado()) {
                                hora = horario.get(x).getHorario().get(y).getHoraInicio()+" a "+horario.get(x).getHorario().get(y).getHoraFinal();
                                break;
                            }
                        }
                        if(!hora.equals(""))
                            break;
                    }
                }
                datos = new String[] {dia, hora}; 
                datos(cabeza, datos);
                break;
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        frmInterno.setVisible(false);                
        frmCalendario.tblHorario.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCalendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCalendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCalendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCalendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCalendario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbSemestre;
    public static javax.swing.JInternalFrame frmInterno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JLabel lblCabeza1;
    private static javax.swing.JLabel lblCabeza2;
    private static javax.swing.JLabel lblCabeza3;
    private static javax.swing.JLabel lblCabeza4;
    private static javax.swing.JLabel lblDato1;
    private static javax.swing.JLabel lblDato2;
    private static javax.swing.JLabel lblDato3;
    private static javax.swing.JLabel lblDato4;
    public static javax.swing.JDesktopPane pnlDesktop;
    public static javax.swing.JTable tblHorario;
    // End of variables declaration//GEN-END:variables
}


class TableButtonRenderer extends JButton implements TableCellRenderer {
    
    private TableCellRenderer defaultRenderer;

    public TableButtonRenderer(TableCellRenderer renderer) {
        defaultRenderer = renderer;
    }

    public Component getTableCellRendererComponent(JTable table,Object value,boolean isSelected,boolean hasFocus,int row,int column)
    {
        if(value instanceof Component)
            return (Component)value;
        return defaultRenderer.getTableCellRendererComponent(table,value,isSelected,hasFocus,row,column);
    }
    
    
}

class TableButtonModel extends AbstractTableModel {
    
    private ArrayList<Vector> rows;
    private String[] columns;

    public TableButtonModel(ArrayList<Vector> data, String[] column) {
        rows = data;
        columns = column;
    }
   
    @Override
    public String getColumnName(int column) { 
        return columns[column];
    }

    @Override
    public int getRowCount() {
        return rows.size();
    }

    @Override
    public int getColumnCount() {
        return columns.length;
    }

    @Override
    public Object getValueAt(int row, int column) { 
        for(int i=0; i < rows.size(); i++) {
            for(int j=0; j < rows.get(i).size(); j++) {
                if(i==row & j==column)
                    return rows.get(i).get(j);
            }
        }
        return null;
    }

    @Override
    public boolean isCellEditable(int row, int column) {
        return false;
    }

    @Override
    public Class getColumnClass(int column) {
        return getValueAt(0, column).getClass();
    }
}

class TableButtonMouseListener implements MouseListener {
    private JTable table;
    JButton button;
    JInternalFrame window = new JInternalFrame("ventana");
    
    private void EventToButton(MouseEvent e) {
        TableColumnModel columnModel = table.getColumnModel();
        int column = columnModel.getColumnIndexAtX(e.getX());
        int row    = e.getY() / table.getRowHeight();
        Object value;
        
        if(row >= table.getRowCount() || row < 0 || column >= table.getColumnCount() || column < 0)
            return;

        value = table.getValueAt(row, 0);

        if(!(value instanceof JButton))
            return;
        button = (JButton)value;
        frmCalendario.frmInterna(button.getText(), column);
        frmCalendario.frmInterno.setVisible(true);   
        frmCalendario.tblHorario.setEnabled(false);
        table.repaint();
    }
    
    public TableButtonMouseListener(JTable table) {
        this.table = table;
    }

    @Override
    public void mouseClicked(MouseEvent e) {
        EventToButton(e);
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        //EventToButton(e);
    }

    @Override
    public void mouseExited(MouseEvent e) {
        //EventToButton(e);
    }

    @Override
    public void mousePressed(MouseEvent e) {
        //EventToButton(e);
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        //EventToButton(e);
    }
}
