/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.Asignatura.Asignatura;
import Datos.Asignatura.Departamento;
import Datos.Asignatura.Practica;
import Datos.Asignatura.Teorica;
import Datos.Usuario.Coordinador;
import Datos.Usuario.Estudiante;
import Datos.Usuario.Profesor;
import Datos.Usuario.Usuario;
import Negocio.ArchivoCls;
import Negocio.AsignaturaCls;
import Negocio.AulaCls;
import Negocio.CalendarioCls;
import Negocio.DepartamentoCls;
import Negocio.UsuarioCls;
import static Presentacion.frmCalendario.tblHorario;
import java.awt.Dimension;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.table.TableCellRenderer;
import javax.xml.bind.Marshaller;
import javax.xml.bind.Marshaller.Listener;
import javax.xml.bind.Unmarshaller;

/**
 *  Ventana que muestra las diferentes acciones que puede ejecutar el usuario administrador
 * @author Daniel Berrocal
 * @author Jorge Rojas
 */
public class V_Coordinador extends javax.swing.JFrame {

    /**
     * Creates new form V_Coordinador
     */
    ArchivoCls file = new ArchivoCls();
    DepartamentoCls depart= new DepartamentoCls();
    UsuarioCls user=new UsuarioCls();
    DefaultListModel modelo = new DefaultListModel();
    ArrayList<String> materiales =new ArrayList();
    
    
    public V_Coordinador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        table = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_Asig_ID = new javax.swing.JTextField();
        txt_Asig_Name = new javax.swing.JTextField();
        txt_Asig_Group = new javax.swing.JTextField();
        txt_Asig_Sem = new javax.swing.JTextField();
        txt_Asig_Cred = new javax.swing.JTextField();
        bADD = new javax.swing.JButton();
        txt_Asig_Variable = new javax.swing.JTextField();
        jLabel_Variable = new javax.swing.JLabel();
        txt_Asig_Material = new javax.swing.JTextField();
        jLabel_Material = new javax.swing.JLabel();
        jComboDep = new javax.swing.JComboBox();
        jcProfe = new javax.swing.JComboBox();
        bOK = new javax.swing.JButton();
        tipo_asig = new javax.swing.JComboBox();
        jbAdd_Material = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Prof_Name = new javax.swing.JTextField();
        txt_Prof_User = new javax.swing.JTextField();
        txt_Prof_ID = new javax.swing.JTextField();
        txt_Prof_Pass = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jcombo_depart = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_Est_Name = new javax.swing.JTextField();
        txt_Est_User = new javax.swing.JTextField();
        txt_Est_Pass = new javax.swing.JTextField();
        txt_Est_Id = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_Coor_Name = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_Coor_User = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_Coor_Pass = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jCombo_Semestre = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaUser = new javax.swing.JList();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Coordinador");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        table.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tableStateChanged(evt);
            }
        });
        table.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                tableVetoableChange(evt);
            }
        });

        jLabel12.setText("Id:");

        jLabel13.setText("Name:");

        jLabel14.setText("Group:");

        jLabel15.setText("Semester:");

        jLabel16.setText("Credits:");

        txt_Asig_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Asig_IDActionPerformed(evt);
            }
        });

        txt_Asig_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Asig_NameActionPerformed(evt);
            }
        });

        bADD.setText("Add");
        bADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bADDActionPerformed(evt);
            }
        });

        jLabel_Variable.setText("Link");

        txt_Asig_Material.setVisible(false);

        jLabel_Material.setText("Materials");
        jLabel_Material.setVisible(false);

        bOK.setVisible(false);
        bOK.setText("OK");
        bOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOKActionPerformed(evt);
            }
        });

        tipo_asig.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Teoric", "Practice" }));
        tipo_asig.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipo_asigItemStateChanged(evt);
            }
        });
        tipo_asig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_asigActionPerformed(evt);
            }
        });

        jbAdd_Material.setVisible(false);
        jbAdd_Material.setText("Add");
        jbAdd_Material.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdd_MaterialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipo_asig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jbAdd_Material)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel_Variable))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_Asig_Cred, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                        .addComponent(txt_Asig_Sem)
                                        .addComponent(txt_Asig_Group)
                                        .addComponent(txt_Asig_Name)
                                        .addComponent(txt_Asig_ID)
                                        .addComponent(txt_Asig_Variable, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(bADD)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                                    .addComponent(bOK)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_Material)
                                .addComponent(txt_Asig_Material, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcProfe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tipo_asig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_Asig_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcProfe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_Asig_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_Asig_Group, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_Material)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_Asig_Sem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_Asig_Material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(txt_Asig_Cred, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAdd_Material))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Asig_Variable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Variable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bADD)
                    .addComponent(bOK))
                .addContainerGap())
        );

        table.addTab("Add Course", jPanel4);

        jLabel1.setText("Name:");

        jLabel2.setText("Username:");

        jLabel3.setText("Password:");

        jLabel4.setText("ID:");

        txt_Prof_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Prof_NameActionPerformed(evt);
            }
        });

        txt_Prof_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Prof_UserActionPerformed(evt);
            }
        });

        txt_Prof_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Prof_IDActionPerformed(evt);
            }
        });

        txt_Prof_Pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Prof_PassActionPerformed(evt);
            }
        });

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Prof_Pass, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(txt_Prof_User)
                            .addComponent(txt_Prof_Name)
                            .addComponent(txt_Prof_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)))
                    .addComponent(jcombo_depart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Prof_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Prof_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Prof_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Prof_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcombo_depart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jButton1)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        table.addTab("Add Teacher", jPanel1);

        jLabel5.setText("Name:");

        jLabel6.setText("Username:");

        jLabel7.setText("Password:");

        jLabel8.setText("ID:");

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Est_Id)
                            .addComponent(txt_Est_Pass)))
                    .addComponent(jButton2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Est_User, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Est_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_Est_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_Est_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txt_Est_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txt_Est_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        table.addTab("Add Student", jPanel2);

        jLabel9.setText("Name:");

        jLabel10.setText("Username:");

        jLabel11.setText("Password:");

        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txt_Coor_Pass))
                    .addComponent(jButton3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Coor_User, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Coor_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_Coor_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_Coor_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txt_Coor_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        table.addTab("Add Coordinator", jPanel3);

        jCombo_Semestre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "I Semester", "II Semester" }));

        jButton4.setText("Generate");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCombo_Semestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap(357, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCombo_Semestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        table.addTab("Schedule", jPanel5);

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listaUser);

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Edit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Reset All");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(table)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(Exit))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Exit)
                            .addComponent(jButton7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton6))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new V_Sign_in().show();
    }//GEN-LAST:event_ExitActionPerformed
    /**
     * Boton que agrega un nuevo profesor a la lista de usuarios y lo guarda en el archivo indicado
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String n = txt_Prof_Name.getText();
        String u =txt_Prof_User.getText();
        String p=txt_Prof_Pass.getText();
        String id=txt_Prof_ID.getText();
        String depa =jcombo_depart.getSelectedItem().toString();
        
        if (n.isEmpty()||u.isEmpty()||p.isEmpty()||id.isEmpty()){
            new V_Alerta_Coor().show();
        }
        else{
            Datos.Usuario.Profesor prof = new Profesor(n, u, p, id);
            UsuarioCls.getUsuario().add(prof);
            
            DepartamentoCls.getDepartamento(depa).agregar(prof);
            //Departamento.getProfesor().add(prof);
            for(int i =0; i<UsuarioCls.getUsuario().size();i++){
               if (UsuarioCls.getUsuario().get(i).getClass().getSimpleName().equals("Profesor")){
                    modelo.addElement((UsuarioCls.getUsuario().get(i).getNombre()).toString() + "  ( Teacher )");
                }       
            }
            listaUser.setModel(modelo);            
        }
        ArrayList<Object> lista = new ArrayList();
        for(int i=0;i<UsuarioCls.getUsuario().size();i++){
            lista.add(UsuarioCls.getUsuario().get(i));
        } 
        file.guardar("usuario", lista);
        txt_Prof_Name.setText("");
        txt_Prof_User.setText("");
        txt_Prof_Pass.setText("");
        txt_Prof_ID.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_Prof_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Prof_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Prof_IDActionPerformed

    private void txt_Prof_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Prof_UserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Prof_UserActionPerformed

    private void txt_Prof_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Prof_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Prof_NameActionPerformed

    private void txt_Prof_PassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Prof_PassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Prof_PassActionPerformed
    /**
     * Boton que agrega un nuevo estudiante a la lista de usuarios y lo guarda en el archivo indicado
     * @param evt 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String n = txt_Est_Name.getText();
        String u =txt_Est_User.getText();
        String p=txt_Est_Pass.getText();
        String id=txt_Est_Id.getText();
        modelo.clear();
        
        if (n.isEmpty()||u.isEmpty()||p.isEmpty()||id.isEmpty()){
            new V_Alerta_Coor().show();
        }
        else{
            Datos.Usuario.Estudiante est = new Estudiante(n, u, p, id);
            UsuarioCls.getUsuario().add(est);
            for(int i =0; i<UsuarioCls.getUsuario().size();i++){
               if (UsuarioCls.getUsuario().get(i).getClass().getSimpleName().equals("Estudiante")){
                    modelo.addElement((UsuarioCls.getUsuario().get(i).getNombre()).toString());
                }       
            }
            listaUser.setModel(modelo);            
        }
        ArrayList<Object> lista = new ArrayList();
        for(int i=0;i<UsuarioCls.getUsuario().size();i++){
            lista.add(UsuarioCls.getUsuario().get(i));
        } 
        file.guardar("usuario", lista);
        txt_Est_Name.setText("");
        txt_Est_User.setText("");
        txt_Est_Pass.setText("");
        txt_Est_Id.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed
    /**
     * Boton que agrega un nuevo coordinador a la lista de usuarios y lo guarda en el archivo indicado
     * @param evt 
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String n = txt_Coor_Name.getText();
        String u =txt_Coor_User.getText();
        String p=txt_Coor_Pass.getText();
        modelo.clear();
        if (n.isEmpty()||u.isEmpty()||p.isEmpty()){
            new V_Alerta_Coor().show();
        }
        else{
            Datos.Usuario.Coordinador coor = new Coordinador(n, u, p);
            UsuarioCls.getUsuario().add(coor);
            for(int i =0; i<UsuarioCls.getUsuario().size();i++){
               if (UsuarioCls.getUsuario().get(i).getClass().getSimpleName().equals("Coordinador")){
                    modelo.addElement((UsuarioCls.getUsuario().get(i).getNombre()).toString());
                }       
            }
            listaUser.setModel(modelo);
            }
        ArrayList<Object> lista = new ArrayList();
        for(int i=0;i<UsuarioCls.getUsuario().size();i++){
            lista.add(UsuarioCls.getUsuario().get(i));
        } 
        file.guardar("usuario", lista);
        txt_Coor_Name.setText("");
        txt_Coor_User.setText("");
        txt_Coor_Pass.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed
    /**
     * Boton que agrega una nueva asignatura, esta asignatura se le asigna a un profesor y a un departamendo, y la guarda en el archivo indicado
     * @param evt 
     */
    private void bADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bADDActionPerformed
        // TODO add your handling code here:
        String id =txt_Asig_ID.getText();
        String n = txt_Asig_Name.getText();
        int g =0;
        int s=0;
        int c=0;
        String var = txt_Asig_Variable.getText();
        String depa = jComboDep.getSelectedItem().toString();
        String profesor =jcProfe.getSelectedItem().toString();
        modelo.clear();
        try{
            g= (int)Integer.parseInt(txt_Asig_Group.getText());
        }
        catch(Exception e){
            txt_Asig_Group.setText("This field can only contain numbers");
        }
        try{
           s = (int)Integer.parseInt(txt_Asig_Sem.getText());
       }
       catch(Exception e){
           txt_Asig_Sem.setText("This field can only contain numbers");
       }
       try{
             c = (int)Integer.parseInt(txt_Asig_Cred.getText());
        }
        catch(Exception e){
            txt_Asig_Cred .setText("This field can only contain numbers");
        }
        
        if (id.isEmpty()||n.isEmpty()){
                new V_Alerta_Coor().show();
            }
            else{
                if (tipo_asig.getSelectedItem().toString().equals("Teoric")){
                Teorica teo = new Teorica(id,n,g,s,c,var);
               
                DepartamentoCls.getDepartamento(depa).agregar(teo);
                DepartamentoCls.getDepartamento(depa).getProfesor(profesor).agregar(teo);
                for(int i =0; i<DepartamentoCls.getDepartamento().size();i++){
                    if (DepartamentoCls.getDepartamento(depa).getAsignatura().get(i).getClass().getSimpleName().equals("Teorica")){
                        modelo.addElement(DepartamentoCls.getDepartamento(depa).getAsignatura().get(i).getNombre().toString() + "  ( Teoric )");
                    }
                }
            }
            else{
                Practica prac = new Practica(id,n, g, s, c,var);
                prac.agregarMateriales(materiales);
                DepartamentoCls.getDepartamento(depa).agregar(prac);
                DepartamentoCls.getDepartamento(depa).getProfesor(profesor).agregar(prac);
               
                for(int i =0; i<DepartamentoCls.getDepartamento().size();i++){
                    if (DepartamentoCls.getDepartamento(depa).getAsignatura().get(i).getClass().getSimpleName().equals("Practica")){
                        modelo.addElement(DepartamentoCls.getDepartamento(depa).getAsignatura().get(i).getNombre().toString() + "  ( Practice )");
                    }
                }
            }
            listaUser.setModel(modelo);
            txt_Asig_Cred.setText("");
            txt_Asig_Group.setText("");
            txt_Asig_ID.setText("");
            txt_Asig_Material.setText("");
            txt_Asig_Name.setText("");
            txt_Asig_Sem.setText("");
            txt_Asig_Variable.setText("");
            materiales.clear();
        }
         
        depart.guardar();
    }//GEN-LAST:event_bADDActionPerformed

   
    
   /**
     * Accion de la interfaz que carga diferentes datos en los combobox indicados
     * @param evt 
     */
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        file.cargar();
        for (int i =0; i< DepartamentoCls.getDepartamento().size();i++){
            jcombo_depart.addItem(DepartamentoCls.getDepartamento().get(i).getDepartamento());
            jComboDep.addItem(DepartamentoCls.getDepartamento().get(i).getDepartamento());
            //System.out.println("hola");
        }
        for (int i =0; i< UsuarioCls.getUsuario().size();i++){
            String s = UsuarioCls.getUsuario().get(i).getClass().getSimpleName();
            String m=Profesor.class.getSimpleName();
            if(UsuarioCls.getUsuario().get(i).getClass().equals(Profesor.class)){
                    jcProfe.addItem(((Profesor)UsuarioCls.getUsuario().get(i)).getNombre());
                }
            
            
        }    
        
        
    }//GEN-LAST:event_formComponentShown

    private void tableVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_tableVetoableChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tableVetoableChange
String tab="";
    private void tableStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tableStateChanged
        // TODO add your handling code here:
        //System.out.println(table.getTitleAt(table.getSelectedIndex()));
        tab = table.getTitleAt(table.getSelectedIndex());
        if (tab.equals("Add Teacher")){
            modelo.clear();
            for(int i =0; i<UsuarioCls.getUsuario().size();i++){
               if (UsuarioCls.getUsuario().get(i).getClass().getSimpleName().equals("Profesor")){
                    modelo.addElement((UsuarioCls.getUsuario().get(i).getNombre()).toString());
                }       
            }
            listaUser.setModel(modelo);
                System.out.println(1);
        }
        if (tab.equals("Add Student")){
            modelo.clear();
            for(int i =0; i<UsuarioCls.getUsuario().size();i++){
               if (UsuarioCls.getUsuario().get(i).getClass().getSimpleName().equals("Estudiante")){
                    modelo.addElement((UsuarioCls.getUsuario().get(i).getNombre()).toString());
                }       
            }
            listaUser.setModel(modelo);   
                System.out.println(2);
        }
        if (tab.equals("Add Coordinator")){
            modelo.clear();
            for(int i =0; i<UsuarioCls.getUsuario().size();i++){
               if (UsuarioCls.getUsuario().get(i).getClass().getSimpleName().equals("Coordinador")){
                    modelo.addElement((UsuarioCls.getUsuario().get(i).getNombre()).toString());
                }       
            }
            listaUser.setModel(modelo);
                System.out.println(3);
        }
        if (tab.equals("Add Course")){
            modelo.clear();
            for(int i =0; i<DepartamentoCls.getDepartamento().size();i++){
                for(int j=0;j<DepartamentoCls.getDepartamento().get(i).getAsignatura().size();j++){
                    
                   modelo.addElement(DepartamentoCls.getDepartamento().get(i).getAsignatura().get(j).getNombre().toString());
                    
                }
            }
            listaUser.setModel(modelo);
                System.out.println(4);
        }
        
    }//GEN-LAST:event_tableStateChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        tab = table.getTitleAt(table.getSelectedIndex());
        String selec=listaUser.getSelectedValue().toString();
        
        if (tab.equals("Add Course")){
            //for(Departamento dep:DepartamentoCls.getDepartamento()){
           DepartamentoCls.deleteAsig(selec);
           modelo.removeElement(selec);
           listaUser.setModel(modelo);
            
        }
        else{
            UsuarioCls.deleteUser(selec);
            modelo.removeElement(selec);
            listaUser.setModel(modelo);
            
            
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        tab = table.getTitleAt(table.getSelectedIndex());
        String selec=listaUser.getSelectedValue().toString();
        
        if (tab.equals("Add Course")){
            Asignatura asi = DepartamentoCls.getAsig(selec);

            bOK.setVisible(true);
            bADD.setVisible(false);

            if (asi instanceof Teorica){
                txt_Asig_Cred.setText(((Integer)(asi.getCreditos())).toString());
                txt_Asig_Group.setText(((Integer)(asi.getGrupo())).toString());
                txt_Asig_ID.setText(asi.getCodigo());
                txt_Asig_Name.setText(asi.getNombre());
                txt_Asig_Sem.setText(((Integer)(asi.getSemestre())).toString());
                Teorica teo=(Teorica)asi;
                txt_Asig_Variable.setText(teo.getPagina());
                Profesor prof=UsuarioCls.getProfesorporAsignatura(selec);
                jcProfe.setSelectedItem(prof.getNombre());                
            }
            else{
                txt_Asig_Cred.setText(((Integer)(asi.getCreditos())).toString());
                txt_Asig_Group.setText(((Integer)(asi.getGrupo())).toString());
                txt_Asig_ID.setText(asi.getCodigo());
                txt_Asig_Material.setText("");
                txt_Asig_Name.setText(asi.getNombre());
                txt_Asig_Sem.setText(((Integer)(asi.getSemestre())).toString());
                Practica prac=(Practica)asi;
                txt_Asig_Variable.setText(prac.getSistema());
                Profesor prof=UsuarioCls.getProfesorporAsignatura(selec);
                jcProfe.setSelectedItem(prof.getNombre());
                jbAdd_Material.setVisible(true);
                jLabel_Material.setVisible(true);
                txt_Asig_Material.setVisible(true);
                jLabel_Variable.setText("System");
                Departamento depart=DepartamentoCls.getDepartamentoporAsignatura(selec);
                jComboDep.setSelectedItem(depart.getDepartamento());
            }
            
           
            
        }
        else{
            
            
        }
    }//GEN-LAST:event_jButton6ActionPerformed


    private void bOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOKActionPerformed
        // TODO add your handling code here:
        
        String selec=listaUser.getSelectedValue().toString();
        Asignatura asi = DepartamentoCls.getAsig(selec);
        asi.setCodigo(txt_Asig_ID.getText());
        asi.setCreditos(Integer.parseInt(txt_Asig_Cred.getText()));
        asi.setGrupo(Integer.parseInt(txt_Asig_Group.getText()));
        asi.setNombre(txt_Asig_Name.getText());
        asi.setSemestre(Integer.parseInt(txt_Asig_Sem.getText()));
        if (asi instanceof Teorica){
            Teorica teo =(Teorica)asi;
            teo.setPagina(txt_Asig_Variable.getText());
        }
        else{
            Practica prac =(Practica)asi;
            prac.setSistema(txt_Asig_Variable.getText());
            prac.setMaterial(materiales);
        }
        
        depart.guardar();
           
        
    }//GEN-LAST:event_bOKActionPerformed

//GEN-FIRST:event_asig_tipoItemStateChanged
 
//GEN-LAST:event_asig_tipoItemStateChanged

    private void txt_Asig_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Asig_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Asig_NameActionPerformed

    private void txt_Asig_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Asig_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Asig_IDActionPerformed

    private void tipo_asigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_asigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_asigActionPerformed

    private void tipo_asigItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipo_asigItemStateChanged
        // TODO add your handling code here:
        String st=tipo_asig.getSelectedItem().toString();
        
        if(st.equals("Practice")){
            //System.out.println(st);
            jLabel_Variable.setText("System");
            jbAdd_Material.setVisible(true);
            txt_Asig_Material.setVisible(true);
            jLabel_Material.setVisible(true);
        }
        else{
        jLabel_Variable.setText("Link");
        jbAdd_Material.setVisible(false);
        txt_Asig_Material.setVisible(false);
        jLabel_Material.setVisible(false);
        }
    }//GEN-LAST:event_tipo_asigItemStateChanged

    private void jbAdd_MaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdd_MaterialActionPerformed
        // TODO add your handling code here:
        materiales.add(txt_Asig_Material.getText());
        txt_Asig_Material.setText("");
        
    }//GEN-LAST:event_jbAdd_MaterialActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new frmCalendario().show();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        new Reset().show();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Coordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Coordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Coordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Coordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Coordinador().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton bADD;
    private javax.swing.JButton bOK;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboDep;
    public static javax.swing.JComboBox jCombo_Semestre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabel_Material;
    public javax.swing.JLabel jLabel_Variable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbAdd_Material;
    private javax.swing.JComboBox jcProfe;
    private javax.swing.JComboBox jcombo_depart;
    private javax.swing.JList listaUser;
    private javax.swing.JTabbedPane table;
    private javax.swing.JComboBox tipo_asig;
    private javax.swing.JTextField txt_Asig_Cred;
    private javax.swing.JTextField txt_Asig_Group;
    private javax.swing.JTextField txt_Asig_ID;
    public javax.swing.JTextField txt_Asig_Material;
    private javax.swing.JTextField txt_Asig_Name;
    private javax.swing.JTextField txt_Asig_Sem;
    private javax.swing.JTextField txt_Asig_Variable;
    private javax.swing.JTextField txt_Coor_Name;
    private javax.swing.JTextField txt_Coor_Pass;
    private javax.swing.JTextField txt_Coor_User;
    private javax.swing.JTextField txt_Est_Id;
    private javax.swing.JTextField txt_Est_Name;
    private javax.swing.JTextField txt_Est_Pass;
    private javax.swing.JTextField txt_Est_User;
    private javax.swing.JTextField txt_Prof_ID;
    private javax.swing.JTextField txt_Prof_Name;
    private javax.swing.JTextField txt_Prof_Pass;
    private javax.swing.JTextField txt_Prof_User;
    // End of variables declaration//GEN-END:variables
}
